/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guimahasiswa;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormNilaiMhs extends javax.swing.JFrame {
    
    Connection con;
    DefaultTableModel modelTabel;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormNilaiMhs.class.getName());

    public FormNilaiMhs() {
        initComponents();
        
        try {
            DBConnection dbConn = new DBConnection();
            con = dbConn.getConnection();
            modelTabel = (DefaultTableModel) jTable2.getModel();
            refreshUI(); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal koneksi ke database!");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nUTS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nUAS = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nTUGAS = new javax.swing.JTextField();
        proses = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        tambahlain = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        proses1 = new javax.swing.JButton();
        update = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        uts35 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nakhir = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        uas35 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        predikat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tugas30 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nhuruf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nim");

        nim.addActionListener(this::nimActionPerformed);

        jLabel3.setText("Nilai UTS");

        nUTS.addActionListener(this::nUTSActionPerformed);

        jLabel4.setText("Nama");

        nama.addActionListener(this::namaActionPerformed);

        jLabel5.setText("Nilai UAS");

        nUAS.addActionListener(this::nUASActionPerformed);

        jLabel6.setText("Nilai Tugas");

        nTUGAS.addActionListener(this::nTUGASActionPerformed);

        proses.setBackground(new java.awt.Color(102, 102, 255));
        proses.setText("Proses 🔃");
        proses.addActionListener(this::prosesActionPerformed);

        simpan.setBackground(new java.awt.Color(102, 255, 102));
        simpan.setText("Simpan ✅");
        simpan.addActionListener(this::simpanActionPerformed);

        tambahlain.setBackground(new java.awt.Color(255, 255, 204));
        tambahlain.setText("Tambah Lain");
        tambahlain.addActionListener(this::tambahlainActionPerformed);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setText("Form Nilai Mahasiswa");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        proses1.setBackground(new java.awt.Color(102, 102, 255));
        proses1.setText("Proses 🔃");
        proses1.addActionListener(this::proses1ActionPerformed);

        update.setBackground(new java.awt.Color(204, 204, 255));
        update.setText("Update ⬆️");
        update.addActionListener(this::updateActionPerformed);

        hapus.setBackground(new java.awt.Color(255, 102, 102));
        hapus.setText("Hapus ❎");
        hapus.addActionListener(this::hapusActionPerformed);

        uts35.addActionListener(this::uts35ActionPerformed);

        jLabel7.setText("UTS35%");

        nakhir.addActionListener(this::nakhirActionPerformed);

        jLabel8.setText("Nilai Akhir");

        uas35.addActionListener(this::uas35ActionPerformed);

        jLabel9.setText("UAS35%");

        predikat.addActionListener(this::predikatActionPerformed);

        jLabel10.setText("Predikat");

        tugas30.addActionListener(this::tugas30ActionPerformed);

        jLabel11.setText("Tugas30%");

        nhuruf.addActionListener(this::nhurufActionPerformed);

        jLabel12.setText("Nilai Huruf");

        keluar.setBackground(new java.awt.Color(204, 204, 204));
        keluar.setText("🔙Keluar");
        keluar.addActionListener(this::keluarActionPerformed);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nim", "Nama", "Nilai UTS", "Nilai UAS", "Nilai Tugas", "Nilai Akhir", "Nilai Huruf", "Predikat"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nTUGAS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(proses)
                                        .addGap(76, 76, 76)
                                        .addComponent(simpan)
                                        .addGap(76, 76, 76)
                                        .addComponent(tambahlain)
                                        .addGap(50, 50, 50))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(keluar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(270, 270, 270))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(proses1)
                        .addGap(78, 78, 78)
                        .addComponent(update)
                        .addGap(86, 86, 86)
                        .addComponent(hapus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uts35, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nakhir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uas35, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(predikat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tugas30, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nhuruf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(nUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(nTUGAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proses)
                    .addComponent(simpan)
                    .addComponent(tambahlain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proses1)
                    .addComponent(update)
                    .addComponent(hapus))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uts35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(uas35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tugas30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(nhuruf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(predikat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  //PTIMASI KODE
    private void kosongkanTextField() {
        nim.setText(""); nama.setText("");
        nUTS.setText(""); nUAS.setText(""); nTUGAS.setText("");
        uts35.setText(""); uas35.setText(""); tugas30.setText("");
        nakhir.setText(""); nhuruf.setText(""); predikat.setText("");
        nim.requestFocus(); 
    }

    private void tampilkanDiTabel() {
        if (modelTabel != null && con != null) {
            modelTabel.setRowCount(0); 
            try {
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM mhs");
                int no = 1;
                while(rs.next()) {
                    Object[] baris = {
                        no++,
                        rs.getString("nim"), rs.getString("nama"),
                        rs.getDouble("nilai_uts"), rs.getDouble("nilai_uas"), rs.getDouble("nilai_tugas"),
                        rs.getDouble("nilai_akhir"), rs.getString("nilai_huruf"), rs.getString("predikat")
                    };
                    modelTabel.addRow(baris);
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    private void refreshUI() {
        kosongkanTextField();
        tampilkanDiTabel();
    }
    private void nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimActionPerformed

    private void nUTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nUTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nUTSActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void nUASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nUASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nUASActionPerformed

    private void nTUGASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nTUGASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nTUGASActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
try {
        String ni = nim.getText();
        String na = nama.getText();
        double ts = Double.parseDouble(nUTS.getText());
        double as = Double.parseDouble(nUAS.getText());
        double tgs = Double.parseDouble(nTUGAS.getText());

        Mhs m = new Mhs(ni, na, ts, as, tgs);

        uts35.setText(String.valueOf(Math.round(m.uts() * 10.0) / 10.0));
        uas35.setText(String.valueOf(Math.round(m.uas() * 10.0) / 10.0));
        tugas30.setText(String.valueOf(Math.round(m.tugas() * 10.0) / 10.0));
        nakhir.setText(String.valueOf(Math.round(m.nilaiAkhir() * 10.0) / 10.0));
        nhuruf.setText(m.getNilHuruf(m.nilaiAkhir()));
        predikat.setText(m.getPredikat(m.getNilHuruf(m.nilaiAkhir())));

    } catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Harap isi angka!");
    }
    }//GEN-LAST:event_prosesActionPerformed

    private void tambahlainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahlainActionPerformed
kosongkanTextField();
    }//GEN-LAST:event_tambahlainActionPerformed

    private void proses1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proses1ActionPerformed
  try {
        String ni = nim.getText();
        String na = nama.getText();
        double ts = Double.parseDouble(nUTS.getText());
        double as = Double.parseDouble(nUAS.getText());
        double tgs = Double.parseDouble(nTUGAS.getText());

        Mhs m = new Mhs(ni, na, ts, as, tgs);

        uts35.setText(String.valueOf(m.uts()));
        uas35.setText(String.valueOf(m.uas()));
        tugas30.setText(String.valueOf(m.tugas()));
        nakhir.setText(String.valueOf(m.nilaiAkhir()));
        nhuruf.setText(m.getNilHuruf(m.nilaiAkhir()));
        predikat.setText(m.getPredikat(m.getNilHuruf(m.nilaiAkhir())));

    } catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Harap isi angka!");
    }
    }//GEN-LAST:event_proses1ActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin hapus?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (konfirmasi == JOptionPane.YES_OPTION) {
        try {
            PreparedStatement ps = con.prepareStatement("DELETE FROM mhs WHERE nim = ?");
            ps.setString(1, nim.getText());
            ps.executeUpdate();
            refreshUI();
        } catch (SQLException ex) {}
    }
    }//GEN-LAST:event_hapusActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
try {
        PreparedStatement ps = con.prepareStatement("UPDATE mhs SET nama=?, nilai_uts=?, nilai_uas=?, nilai_tugas=?, nilai_akhir=?, nilai_huruf=?, predikat=? WHERE nim=?");
        ps.setString(1, nama.getText());
        ps.setString(2, nUTS.getText());
        ps.setString(3, nUAS.getText());
        ps.setString(4, nTUGAS.getText());
        ps.setString(5, nakhir.getText());
        ps.setString(6, nhuruf.getText());
        ps.setString(7, predikat.getText());
        ps.setString(8, nim.getText()); 
        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
        refreshUI(); 
    } catch(SQLException ex) {
        JOptionPane.showMessageDialog(this, "Gagal Update Data!");
    }
    }//GEN-LAST:event_updateActionPerformed

    private void uts35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uts35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uts35ActionPerformed

    private void nakhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nakhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nakhirActionPerformed

    private void uas35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uas35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uas35ActionPerformed

    private void predikatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_predikatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_predikatActionPerformed

    private void tugas30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tugas30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tugas30ActionPerformed

    private void nhurufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhurufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhurufActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
try {
        PreparedStatement ps = con.prepareStatement("INSERT INTO mhs (nim, nama, nilai_uts, nilai_uas, nilai_tugas, nilai_akhir, nilai_huruf, predikat) VALUES (?,?,?,?,?,?,?,?)");
        ps.setString(1, nim.getText());
        ps.setString(2, nama.getText());
        ps.setString(3, nUTS.getText());
        ps.setString(4, nUAS.getText());
        ps.setString(5, nTUGAS.getText());
        ps.setString(6, nakhir.getText());
        ps.setString(7, nhuruf.getText());
        ps.setString(8, predikat.getText());
        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
        refreshUI(); 
    } catch(SQLException ex) {
        JOptionPane.showMessageDialog(this, "Gagal Simpan! Error: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_simpanActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int baris = jTable2.getSelectedRow();
        
        if (baris != -1) {
            //Mengambil data dari tabel dan memasukkan ke Text Field
            nim.setText(jTable2.getValueAt(baris, 1).toString());
            nama.setText(jTable2.getValueAt(baris, 2).toString());
            nUTS.setText(jTable2.getValueAt(baris, 3).toString());
            nUAS.setText(jTable2.getValueAt(baris, 4).toString());
            nTUGAS.setText(jTable2.getValueAt(baris, 5).toString());
            
            //OPTIMASI: Otomatis menghitung ulang Nilai Akhir & Predikat saat di-klik
            prosesActionPerformed(null);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormNilaiMhs().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField nTUGAS;
    private javax.swing.JTextField nUAS;
    private javax.swing.JTextField nUTS;
    private javax.swing.JTextField nakhir;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nhuruf;
    private javax.swing.JTextField nim;
    private javax.swing.JTextField predikat;
    private javax.swing.JButton proses;
    private javax.swing.JButton proses1;
    private javax.swing.JButton simpan;
    private javax.swing.JButton tambahlain;
    private javax.swing.JTextField tugas30;
    private javax.swing.JTextField uas35;
    private javax.swing.JButton update;
    private javax.swing.JTextField uts35;
    // End of variables declaration//GEN-END:variables
}
